name: CI Demo

on:
  push:
    branches:
      - branch-suleyman
  workflow_dispatch:

jobs:
  hello: WELT!
    runs-on: ubuntu-latest
    steps:
      - name: Branch specific output
        run: |
          if [ "$GITHUB_REF_NAME" = "branch-suleyman" ]; then
            echo "‚úÖ Push auf MAIN Branch"
          elif [ "$GITHUB_REF_NAME" = "branch-suleyman" ]; then
            echo "üß™ Push auf BRANCH-SULEYMAN"
          else
            echo "‚ÑπÔ∏è Push auf anderem Branch: $GITHUB_REF_NAME"
          fi
